POST http://localhost:8080/api/users/1/ads
Content-Type: application/json

{
  "category": "ELECTRONICS",
  "price": 5000,
  "place": "Budapest",
  "description": "color TV"
}

###

POST http://localhost:8080/api/users/1/ads
Content-Type: application/json

{
  "category": "VEHICLE",
  "price": 9000,
  "place": "Veszprém",
  "description": "black Volvo"
}

###

POST http://localhost:8080/api/users/2/ads
Content-Type: application/json

{
  "category": "OTHER",
  "price": 500,
  "place": "Szolnok",
  "description": "box"
}

###

GET http://localhost:8080/api/users/ads
Accept: application/json

###

GET http://localhost:8080/api/users/ads/1
Accept: application/json

###

GET http://localhost:8080/api/users/ads?minprice=6000&place=veszprém&cat=vehicle
Accept: application/json

###

PUT http://localhost:8080/api/users/ads/2
Content-Type: application/json

{
  "category": "VEHICLE",
  "price": 19000,
  "place": "Veszprém",
  "description": "black Volvo"
}

###

DELETE http://localhost:8080/api/users/ads/1

