POST http://localhost:8080/api/ads
Content-Type: application/json

{
  "category": "ELECTRONICS",
  "price": 5000,
  "place": "Budapest",
  "description": "színes TV",
  "userId": 1
}

###

POST http://localhost:8080/api/ads
Content-Type: application/json

{
  "category": "VEHICLE",
  "price": 9000,
  "place": "Veszprém",
  "description": "fekete roller",
  "userId": 50
}

###

GET http://localhost:8080/api/ads
Accept: application/json

###

GET http://localhost:8080/api/ads/2
Accept: application/json

###

GET http://localhost:8080/api/ads?minprice=6000&place=VeSzPrÉm&cat=vehicle
Accept: application/json

###

PUT http://localhost:8080/api/ads/2
Content-Type: application/json

{
  "category": "VEHICLE",
  "price": 19000,
  "place": "Veszprém",
  "description": "fekete roller"
}

###

DELETE http://localhost:8080/api/ads/2

