POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "password": "********",
  "email": "johndoe@gmail.com"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "password": "123456",
  "email": "janedoe@gmail.com"
}

###

GET http://localhost:8080/api/users
Accept: application/json

###

GET http://localhost:8080/api/users/1
Accept: application/json

###

PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "name": "John Doe",
  "password": "********",
  "email": "johndoe@gmail.com"
}

###

DELETE http://localhost:8080/api/users/2

